### ISSUE TITLE
rename javascript into web front-end (javascript, css, ...)

### ISSUE THREAD

**Issue by muayyad-alsadi** [jordanopensource/awesome-jordan#24]
[RtlCss](https://github.com/muayyad-alsadi/RtlCss) is a tool written in python to generate RTL css (puting it under python is not a good idea I guess)

[bootstrap 2.x](http://muayyad-alsadi.github.io/bootstrap-rtl/2.x/index.html) and [bootstrap 3.x](http://muayyad-alsadi.github.io/bootstrap-rtl/3.x/index.html) where made using this tool, I guess they won't fall under javascript so I suggest "web front-end" as a better section name

I also have this to add to this section

* [ajax-ops](https://github.com/muayyad-alsadi/ajax-ops)

**Comment by mjalajel** [comment]
@anasAsh what do you think?

**Comment by anasAsh** [comment]
if we do as suggested, should we add a new entry for NodeJs?
or instead of replacing JavaScript with Front-end, how about we add CSS/HTML?

**Comment by anasAsh** [comment]
anyway, i was checking RtlCss now, and it looks like a python code actually that produces css as an output, not sure how we should decide on categorizing inter-technology libraries.

**Comment by muayyad-alsadi** [comment]
There is an already entry for nodejs

http://imgur.com/a/03OsQ

**Comment by mjalajel** [comment]
_I'm just thinking out loud now_

@muayyad-alsadi -- If we're to organize things _correctly_, then we'll have a matrix structure where every library will be under both a `language` section and another `usage` section. (e.g. shell script for unit testing should fall both under `bash` and `testing`)... I admit that my first instinct to organize things was by language and that this decision was arbitrary.

However, we did break it with the `data science` section since it has repos written in multiple languages.

Personally, I prefer keeping things as-is and add these libraries under `python` (for now). Once we have a larger set of libraries we can re-organize them all by functionality rather than language. (maybe in a month or two).

@muayyad-alsadi @anasAsh what do you think?

**Comment by muayyad-alsadi** [comment]
yes, I support split by usage (ex. data science, docker, front-end, ..)
unless it's a language specific library,

that's why the RtlCss python should go in front-end not python. because it's used as a tool not a library.

and usually javascript and css are very related (front end)
on the other hand nodejs is very different (worth being split just like python libraries ) and not put nodejs and javascript as one section

**Comment by anasAsh** [comment]
I agree, on front end they invent a new language every day 😂, i am with splitting by usage instead of language.

**Comment by mjalajel** [comment]
@anasAsh okay, can you create the new section please and move existing repos to it? (make sure they're ordered alphabetically)

**Comment by muayyad-alsadi** [comment]
feel free to add the 4 projects above to it (RtlCss, bootstrap rtl 2.x, 3.x, and ajax-ops)

**Comment by yazd** [comment]
FWIW, my DKit project is written in python but is under D. I vote for usage based categorization.
